runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /css
  static_dir: templates/stylesheets
  mime_type: text/css

- url: /.*
  script: main.app

libraries:
- name: jinja2
  version: latest
